# Dependencies
highlighter:      rouge
markdown:         kramdown
theme:            Minimal

# Permalinks
permalink:        pretty

# Setup
title:            OvercodedStack
tagline:          'Stacked'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:               
baseurl:          "OvercodedStack.github.io"
author:
  name:            
  url:             

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:            
